HELP_DESCRIPTION = 'CLIBooks - A Command Line Interface for Books management'
HELP_MODES = 'CLIBooks operation modes to choose from'
HELP_ID = 'book ID - mandatory for DELETE and CHANGE STATUS modes'
HELP_TITLE = 'book Title - mandatory for ADD mode, optional for FIND mode'
HELP_AUTHOR = 'book Author - mandatory for ADD mode, optional for FIND mode'
HELP_YEAR = 'book Year - mandatory for ADD mode, optional for FIND mode'
HELP_STATUS = 'book Status - mandatory for CHANGE STATUS mode (0 for not available, 1 for available)'

MISSING_PARAMETERS_MESSAGE = 'One or more mandatory parameters missing'
SUCCESS_MESSAGE = 'Operation completed successfully'
NOT_FOUND_MESSAGE = 'Could not find the object with specified parameters'
